name: OpenAQ python bug
description: Report a bug or unexpected behavior in OpenAQ python wrapper
labels: [bug, pending]

body:
  - type: markdown
    attributes:
      value:  Thank you for contributing to OpenAQ Python

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible.
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: >
        If applicable, please add a self-contained,
        [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example)
        demonstrating the bug.
      render: Python

  - type: textarea
    id: version
    attributes:
      label: Python, openaq & OS Version
      description: |
        Which version of Python & OpenAQ python are you using, and which Operating System?

        Please run the following command and copy the output below:

        ```bash
        python -c "import openaq.version; print(openaq.version.version_info())"
        ```

      render: Text
    validations:
      required: true