blank_issues_enabled: false

contact_links:
  - name: Ask a question / advice on using OpenAQ
    url: https://join.slack.com/t/openaq/shared_invite/zt-yzqlgsva-v6McumTjy2BZnegIK9XCVw
    about: Connect with OpenAQ community